version: 0.0
os: ubuntu
files:
  - source: /frontend
    destination: /home/ubuntu/hashtap/hashtap-app/frontend
hooks:
  ApplicationStop:
    - location: /before-install.bat
      timeout: 900  
  BeforeInstall:
    - location: /before-install.bat
      timeout: 900